In [1]:
import numpy as np
import matplotlib.pyplot as plt

path = 'smile.jpg'
img = plt.imread(path)
print(img)
print("min value: ",img.min())
print("max value: ", img.max())
print("mean: ", img.mean())
print("median: ",np.median(img))
print("average: ",np.average(img))
print("mean1: ",np.mean(img))

[[[148 214 238]
  [148 214 238]
  [148 214 238]
  ...
  [162 219 239]
  [162 219 239]
  [162 219 239]]

 [[148 214 238]
  [148 214 238]
  [148 214 238]
  ...
  [162 219 239]
  [162 219 239]
  [162 219 239]]

 [[149 215 239]
  [149 215 239]
  [149 215 239]
  ...
  [163 218 239]
  [163 218 239]
  [163 218 239]]

 ...

 [[241 237 234]
  [242 238 235]
  [243 239 236]
  ...
  [111 177 209]
  [111 177 209]
  [111 177 209]]

 [[242 238 235]
  [242 238 235]
  [243 239 236]
  ...
  [109 178 209]
  [110 179 210]
  [110 179 210]]

 [[242 238 235]
  [242 238 235]
  [243 239 236]
  ...
  [109 178 209]
  [110 179 210]
  [110 179 210]]]
min value:  0
max value:  255
mean:  183.14847417840375
median:  210.0
average:  183.14847417840375
mean1:  183.14847417840375
