In [3]:
import numpy as np
import matplotlib.pyplot as plt

path = 'coins.jpg'#resim
img = plt.imread(path)#okuma
print(img)#resmin matrisi
print("type: ",type(img))#resmin tipi
print("shape: ",img.shape)#resmin kaça kaçlık olduğu
print("ndim: ",img.ndim)#resmin dizi boyutunun sayısı.
print("size: ",img.size)#resmin boyutu
print("dtype:", img.dtype)#resmin veri tipi

print("red channel: ",img[50,50,0]) # rgb--> r =0, g=1, b=2
print("green channel: ",img[50,50,1])
print("blue channel: ",img[50,50,2])
print("rgb channel value: ",img[50,50,:])

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
type:  <class 'numpy.ndarray'>
shape:  (474, 640, 3)
ndim:  3
size:  910080
dtype: uint8
red channel:  182
green channel:  162
blue channel:  111
rgb channel value:  [182 162 111]
