In [1]:
# ndarray --> n-dimensional array

import numpy as np
x = np.array([[-2,-1,0,5],[9,4,5,-7],[9,7,6,5]],np.int16) # unsigned int

print(x)

print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(x.T)

[[-2 -1  0  5]
 [ 9  4  5 -7]
 [ 9  7  6  5]]
(3, 4)
2
int16
12
[[-2  9  9]
 [-1  4  7]
 [ 0  5  6]
 [ 5 -7  5]]
